-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Raakaaine CASCADE;
DROP TABLE IF EXISTS Eines CASCADE;
DROP TABLE IF EXISTS Annos CASCADE;
DROP TABLE IF EXISTS Paivanravinto CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Annosraakaaine CASCADE;